apiVersion: skaffold/v4beta5
kind: Config
build:
  artifacts:
    # - image: us.gcr.io/ticketing-dev-388406/auth
    - image: juniorotero/auth
      context: auth
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
      docker:
        dockerfile: Dockerfile
  local:
    push: false
  # googleCloudBuild:
  #   projectId: ticketing-dev-388406
manifests:
  rawYaml:
    - ./infra/k8s/*
deploy:
  kubectl: {}
